// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cg_content
Rcpp::DoubleVector cg_content(Rcpp::StringVector myvector);
RcppExport SEXP PJsTools_cg_content(SEXP myvectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type myvector(myvectorSEXP);
    rcpp_result_gen = Rcpp::wrap(cg_content(myvector));
    return rcpp_result_gen;
END_RCPP
}
// cpg_content
Rcpp::DoubleVector cpg_content(Rcpp::StringVector myvector);
RcppExport SEXP PJsTools_cpg_content(SEXP myvectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type myvector(myvectorSEXP);
    rcpp_result_gen = Rcpp::wrap(cpg_content(myvector));
    return rcpp_result_gen;
END_RCPP
}
